### ISSUE TITLE
TFC addon

### ISSUE THREAD

**Issue by Harrie1966** [cmik/cmik.xbmc#1]

**Comment by Harrie1966** [comment]
Hi the TFC addon is not working more. TFC has A update 29-5-2017.

**Comment by cmik** [comment]
Hi,
Yes, it is because of the recent changes on TFC.tv website and webservices.
Fixes are ongoing.
I will keep you posted as soon as an RC version will be released.

**Comment by Harrie1966** [comment]
Hi Cmik

thank you very much. It works again happy. good job.
Greetings Harrie

Verstuurd vanaf mijn iPad

**Comment by encar59** [comment]
How do I fix my tfc addon on Amazon  firestick, what repository do I go now to install the addon.

**Comment by cmik** [comment]
@encar59,
You just have to download the repo and copy it on your firestick: https://github.com/cmik/cmik.xbmc/raw/master/downloads/repository.cmik.xbmc.addons/repository.cmik.xbmc.addons-0.0.1.zip
And go to Kodi Settings / Addons / Install from zip
Then when it's installed, go to Settings / Addons / Install from repository / cmik Add-ons / Video Addons /
and install TFC.tv addon
Hope it will help

**Comment by encar59** [comment]
👍👍😀

**Comment by angel628** [comment]
@cmik 
Can you please please! show step by step on how to download the repo?  And what to use adb, adbfire, Downloader?  Been dying to fix TFC!!!

**Comment by cmik** [comment]
Download app called "Downloader".

Launch "Downloader" then enter this shortened URL:
https://goo.gl/4LQcaU

This points to this repository on github:
https://github.com/cmik/cmik.xbmc/raw/ma...-0.0.1.zip

In Kodi v17.3:
1. Navigate to "Install from zip file"
2. Root filesystem -> /sdcard/Downloader/repository.cmik.xbmc.addons-0.0.1.zip
3. Navigate to "Install from repository"

**Comment by angel628** [comment]
Hi Cmik,

Thank you so much for your reply!  It's working now.  You saved my life, everybody's happy especially grandma!!!

**Comment by cmik** [comment]
Normally, you have to select repo cmik Addons / videos addons / TFC.tv

**Comment by codydude1** [comment]
Nuodtayo.tv has just released v1.7 which fixes movies and has live tv. So far its the most perfect version to date.

https://github.com/benaranguren/nuodtayo.tv/tree/master/plugin.video.tfctv

**Comment by encar59** [comment]
How do I install this on firestick.

**Comment by codydude1** [comment]
@encar59 Download this via esfileexplorer. Go to settings, addons, install from zip, internal storage, download folder. You might have to delete your old version of TFC and delete any cookies on esfile explorer if your getting errors. For your conveniece download the fire tv remote app, copy this link on your ipad, use the keyboard function and press the paste icon.

https://github.com/benaranguren/nuodtayo.tv/raw/master/downloads/repository.nuodtayo.tv.addons/repository.nuodtayo.tv.addons-0.0.2.zip
