### ISSUE TITLE
Settings - Episode view list 10, 20, 50

### ISSUE THREAD

**Issue by islandtj** [cmik/cmik.xbmc#10]
Mahalo @cmik, my wife is once again happy! Big mahalo for your efforts...

A request though, within your older versions, we were able to select in the settings section how many episodes (10, 20, 50) we could see and advance. This feature was very convenient when watching a show for the first time and having the ability to advance to the first shows/episodes easily for shows with over 150 episodes. Would you reactivate this feature? 

Mahalo again.

**Comment by cmik** [comment]
@islandtj,
version 0.0.63 is out.
It enables the items per page feature in the addon settings.
You can choose 8, 16, 32, 64, 128 items per page.
Enjoy!
