### ISSUE TITLE
Blurred

### ISSUE THREAD

**Issue by makoychan** [cmik/cmik.xbmc#11]
Hi cmik, i noticed after .58 update the videos are quite blurred and pixelated. Im pretty its not my inet because ive tried using it on my 4g as well and the wifi at my gfs place. My home inet is 100/100 and my gf is verizon  fios 50/50. All came out blurred and pixelated.

**Comment by islandtj** [comment]
This is fixed in the most recent version... Update through cmik's repo.

**Comment by makoychan** [comment]
Hmmm.. maybe i need to do something on the settings? Because i installed .60 ver. And still its pixelated. Using kodi on nvidia shield 100/100 mbs speedtest shows i am around 86mbs currently

**Comment by makoychan** [comment]
Ooppsss.. sorry there was .62 already ill try now tnx amd sorry
