### ISSUE TITLE
No auto update for version .65

### ISSUE THREAD

**Issue by codydude1** [cmik/cmik.xbmc#13]
Can you update the repository so we don't need to manually download the addon.

**Comment by cmik** [comment]
@codydude1 ,
My devices are updating automatically (when I reboot Kodi).
If not, 
Go to general "Settings" > Add-on > "Search for updates" (mine is in menu sidebar).

http://kodi.wiki/view/Add-on_manager#How_to_access_the_Add-on_manager
http://kodi.wiki/view/Add-on_manager#Updating

Also check if you enabled Automatic updates on my repo and TFC.tv addon.

Thanks in advance for your feedback.

**Comment by codydude1** [comment]
I had to reinstall the repository to get latest update .66

**Comment by cmik** [comment]
@codydude1,
Did it update itself automatically to .67?

**Comment by Dave4jc** [comment]
Got another issue, I am in  Premium account. Most of  movies does not play or work.I played #walang forever and it played only up to 17 minutes. old dramas like forever more, etc. does not play. I am using Latest kodi 17.3 TFC .67 on amazon firestick. Please help!!!
