### ISSUE TITLE
pixelation

### ISSUE THREAD

**Issue by apps2011** [cmik/cmik.xbmc#14]
cmik,
just updated to .65 . having pixelation issue as .63

**Comment by eric2three** [comment]
Everything is back to SD again. Hope cmik can fix this. Looks like TFC is messin' with us..

**Comment by cmik** [comment]
version 0.0.66 is available and fix this problem.
We use a secondary Akamai server but it's possible that some new episodes aren't available yet (it takes some time to be updated).
Hope this fix will last longer than the previous one.

**Comment by rockers961** [comment]
0.66 fixed the pixelation issues. Thanks for the hardwork.

**Comment by apps2011** [comment]
thank you cmik

**Comment by jhayne18** [comment]
how do you update on .66? mine still in .65 thanks

**Comment by cmik** [comment]
It seems that initial Akamai server is now working in HD so I've released version 0.0.67.
But I've added an addon option so we can enable to modify the stream server if needed.

**Comment by cmik** [comment]
@jhayne18,
Go to general "Settings" > Add-on > "Search for updates" (mine is in menu sidebar).

http://kodi.wiki/view/Add-on_manager#How_to_access_the_Add-on_manager
http://kodi.wiki/view/Add-on_manager#Updating

Also check if you enabled Automatic updates on my repo and TFC.tv addon.

**Comment by jhayne18** [comment]
ok thanks alot

**Comment by rockers961** [comment]
@cmik have you notice pixelation on ANC live channel? and DZMM isnt working but other than that everything is amazing.. thanks a lot @cmik.

**Comment by jhayne18** [comment]
actually i dnt watch those channel lol but the rest was back to hd thanks for the update
