### ISSUE TITLE
Most movies does not play, old dramas not working

### ISSUE THREAD

**Issue by Dave4jc** [cmik/cmik.xbmc#15]
Got another issue, I am in  Premium account. Most of  movies does not play or work.I played #walang forever and it played only up to 17 minutes. old dramas like forever more, etc. does not play. cleared cache & cookies, still not working.I am using Latest kodi 17.3 TFC .67 on amazon firestick. Please help!!!

**Comment by ricardobothe** [comment]
Using raspberry 3 with OSMC and I have TFC tv premium account.  all movies not able to play. Can you please check ?
