### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by BigMiggen** [cmik/cmik.xbmc#16]
Today I'm having trouble with the addon logging in to my paid tfc. Account. Every time it asks me if I would like to log in I select yes and it then gives an error. It happens on all 3 of our nvidia shields. It was working fine last night

**Comment by BigMiggen** [comment]
Okay so if I say no when it asks me to log in it works fine. My credentials are stored in the app settings so I think that's why it's working. I guess you just have to say no when prompted to login.

**Comment by cmik** [comment]
Hi @BigMiggen,
This issue has been fixed in version 0.68 and above.
