### ISSUE TITLE
TFC Live LInks

### ISSUE THREAD

**Issue by sdstreams** [cmik/cmik.xbmc#17]
Hello 

I was wondering if any way to add the Live streams that are available on the TFC.Tv website for valid subscriptions? There's another developer that has them but has not put out an update to correct playback fail errors. Prior to that the live section has been working perfectly.

Thank you

**Comment by MALCHUSTVKODI** [comment]
Hi , anyone having issues with playback on the latest tfc tv addon pls.seems like i cant play anything at the moment, premium subscriber.is version.0.0.71  the latest update....will post kodi log if i cant it it..the videos just dont play ,no error created??thank adnin...keep up thegood work!!

**Comment by cmik** [comment]
TFC.tv add-on For KODI issues are now [here](https://github.com/cmik/plugin.video.tfctv/issues)
