### ISSUE TITLE
Tfc addon broke today. 

### ISSUE THREAD

**Issue by BigMiggen** [cmik/cmik.xbmc#18]
I'm using an up to date Nvidia shield with kodi 17.5. Your addon was working fine yesterday but today videos won't play, just the spinning circle then nothing. I did a fresh kodi install as well as your repo, tfc.tv. 67. Now clicking on the tfc.tv addon gives an error code. 2 errors in the kodi log about python script error report  "getdirectory - error getting plugin://plugin.video.tfc.tv/)" and "cguimediawindow : :getdirectory(plugin.video.tfctv/) failed

It stopped working this morning on all 3 of my shields, one of which still has kodi 17.4 so I don't think it was 17.5 that broke it. 

Any input is appreciated.

**Comment by BigMiggen** [comment]
Okay, the addon opens now but still getting failed to play errors when trying to watch a show.

**Comment by BigMiggen** [comment]
Did they switch the format to flash player? On their desktop site it's asking me to install flash player which android doesn't support anymore.

**Comment by cmik** [comment]
Hi @BigMiggen,
Did the latest version 0.69 fixed your issue?
It seems I had a similar issue due to fingerprintid expiration used by akamai servers.

**Comment by BigMiggen** [comment]
Yes, all good now. Works great again. Appreciate your support Cmik. Thx again

**Comment by whoopderitis** [comment]
Working again for me, but is anyone else having trouble with the videos buffering now? Videos will also go in this fast forward mode where it looks like the video is skipping (audio cuts out while this is happening). It will only play for a few seconds before it starts buffering again. I didn't have this issue before what happened 3 days ago. Happening in multiple devices too. I have a Matricom G Box and also a Fire Stick.

**Comment by robbylights** [comment]
Hi CMIK, the problem 3 days ago seems to reoccur.

**Comment by BigMiggen** [comment]
Mine isn't working again either. Nothing will play.

**Comment by eric2three** [comment]
Hello Cmik. TFC is not working again as of this morning. It was working fine last night and today the episodes will not play. Thanks for all your hard work. Waiting for your add on update. God bless

**Comment by fhandschuch** [comment]
Not working here either (newest Kodi on OSMC on Vero 4K). I first tried to restart Kodi, then rebooted the Vero. While the asawa was trying to select a show and an episode to play, I did a `tail -f .kodi/temp/kodi.log` and found plenty of entries like the following:

> 17:15:35.578 T:3613361136   ERROR: GetDirectory - Error getting
> 17:16:27.424 T:4108222464   ERROR: Previous line repeats 6 times.
> 17:16:27.424 T:4108222464   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tfctv/?url=141508&mode=4&name=Ep.+31+-+Nov+06%2C+2017&page=0&thumbnail=https%3A%2F%2Fimg.tfc.tv%2Fxcms%2Fepisodeimages%2F141508%2F20171106-good-487-1.jpg]

Hope that helps in some way.

**Comment by cmik** [comment]
Hi all,
It seems a security key has been added to video streams. A fix is ongoing development. Hope to get it to work very soon.

**Comment by nuodtayo** [comment]
Hey @cmik, I added the same random fingerprint as the security key and that got it going.  We should really just work together on this :)

https://github.com/nuodtayo/nuodtayo.tv/commit/7924919f3bd7cb4402777468e184883351ab070e#diff-bd3a1744176b20a03cfc143950e1097d

**Comment by cmik** [comment]
Hi @nuodtayo , 
Just released version 0.71 which implements security key retrieved from TFC.tv JS script (not sure if the fid will work forever as sk).
As I see, you sure have better skills than me on Python development (very clean and advanced code). :)

**Comment by BigMiggen** [comment]
I'm still seeing 69 as the current version, where is 71?

**Comment by BigMiggen** [comment]
Found it. 71 is working. I found it here on gethub. The kodi repo hasn't updated yet.

Thx again cmik

**Comment by makoychan** [comment]
Hi cmik,

Tried .71 but still I get errors on playing.

**Comment by makoychan** [comment]
Hi cmik,

Tried .71 but still I get errors on playing.

**Comment by makoychan** [comment]
Using kodi 17.4, not sure if there is bearing with.

**Comment by ACEB0ND** [comment]
where can i find the version 0.71?

**Comment by BigMiggen** [comment]
You can find it here in downloads or it should auto update if you have cmik repo installed

**Comment by ACEB0ND** [comment]
can somebody comment the shorted url?

**Comment by m1k31804** [comment]
Is there any way to get the Live works? The ANC is SD format not 720, and DZMM Teleradyo not working. 
Thanks

**Comment by BigMiggen** [comment]
You have to switch to desktop view if you are on a mobile browser. https://github.com/cmik/cmik.xbmc/blob/master/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.71.zip

**Comment by ACEB0ND** [comment]
found it . .thank you'll
