### ISSUE TITLE
TFC.tv ver 71 works on my Gen 1, not on Firetv

### ISSUE THREAD

**Issue by arnel300** [cmik/cmik.xbmc#19]
I have updated my addon to .71 and it fixed my Gen 1 firestick. However, the fix did not work for my Firetv. I want to learn how to code open source so hopefully I can contribute. I am retired military with plenty of time on my hand

**Comment by cmik** [comment]
Hi Arnel300,
Can you try to set the addon option Advanced > Enable stream server modification to ON ?
Thanks in advance for your feedback.

**Comment by arnel300** [comment]
I did that... I read your first fix to .71
But it still did not work on my Firetv... it makes me want to learn open
source. I am a retired miltary of 26 years... I have a lot of time on my
hands lately.

**Comment by arnel300** [comment]
I uninstalled TFC.TV and fresh installed .71 again. Amazingly, it worked this time. Thanks for taking the time to check it out.
