### ISSUE TITLE
TFC not working after exit Kodi

### ISSUE THREAD

**Issue by sdstreams** [cmik/cmik.xbmc#2]
When I first install 0.57 and sign in it seems to work perfectly but if I exit Kodi then launch again I get a log error. the only way to get it working is to uninstall then reinstall and sign in. If I exit it won't function anymore. Any help would be appreciated.

**Comment by jcollinsjr** [comment]
Download version 0.58.  It fixes TFC.tv latency issues.

**Comment by cmik** [comment]
Thanks for your feedback.

**Comment by codydude1** [comment]
Nuodtayo.tv has just released v1.7. Fixes missing movies and has live stream. It is the most perfect version to date.

https://github.com/benaranguren/nuodtayo.tv/tree/master/plugin.video.tfctv
