### ISSUE TITLE
Video skipping

### ISSUE THREAD

**Issue by nuttyclub** [cmik/cmik.xbmc#21]
Hi,
Using the latest version of tfc .73
While watching, sometimes it skips forward a few minutes. Lol. It kinda sucks coz u get spoiled if you are watching something and suddenly it shows the ending lol. Please help.
Thank you

**Comment by cmik** [comment]
Hi,
On which plateform are you using TFC addon ?

**Comment by nuttyclub** [comment]
On an android tv box

**Comment by jcollinsjr** [comment]
Where did you download version 0.73 at?

**Comment by nuttyclub** [comment]
I think it was just due to the box im using. All good now.
