### ISSUE TITLE
2 Minute Preview Issue

### ISSUE THREAD

**Issue by rockers961** [cmik/cmik.xbmc#22]
Hi I was trying to see if you guys experience this 2 minute preview? I have a premium account but after a couple of days or a week it switch to a 2 minute preview, the only work around I did was to re-enter my login info, it was OK for me but has been a problem with my Aunt who's not so techie. Hope there is an easy way to prevent this. Thanks CMIK. God Bless

**Comment by jcollinsjr** [comment]
Yeah, I have been also getting this problem. Usually re-installing the add-on does the trick.

**Comment by cmik** [comment]
@rockers961 , @jcollinsjr ,
Version 0.0.72 normally fixes the preview issue when the session has expired.
Enjoy!

**Comment by rockers961** [comment]
@cmik my apologies for the late response, we really appreciate all your effort. God Bless you.
