### ISSUE TITLE
Tfc.tv 

### ISSUE THREAD

**Issue by Panday1980** [cmik/cmik.xbmc#23]
Tfc.tv addon not working. Saying failed commoncache.

**Comment by mamurao** [comment]
Hi i just notice repo version 72 is no longer working on android 4.42.
error is playback error.

it still works for android 5.0

please help

**Comment by mamurao** [comment]
i tried reloading repo and kodi 16.1 as i'm on android 4.42

does kodi 17.x works on android 4.42 ?

**Comment by cmik** [comment]
@Panday1980 and @mamurao ,
Sorry for the late reply on this issue. Are you still encountering these problems ?
Thanks in advance.
