### ISSUE TITLE
Connection Timeout Error

### ISSUE THREAD

**Issue by whoopderitis** [cmik/cmik.xbmc#27]
TFC.tv add-on isn't loading anything. You get a "Connection Timeout Error" show up for https://tfc.tv/profiles. None of the categories shows up for me. I tried logging out and logging back in. Help please?

**Comment by whoopderitis** [comment]
Never mind. Working again. Thank you.

**Comment by arnel300** [comment]
I had similar issue that wont go away. I fixed it by re-installing Kodi,
and the addon... I tried all kinds of tricks, nothing worked. Re-installed
Kodi and no more problem.
