### ISSUE TITLE
TFC Movies not Playing

### ISSUE THREAD

**Issue by bienell18** [cmik/cmik.xbmc#29]
News and shows works fine but the movies gives errors.

**Comment by arnel300** [comment]
Seems like a basic subscription to me. Upgraded subscription should give you access.

**Comment by bienell18** [comment]
I have premium subscription. I can watch movies in tfc.tv website

**Comment by cmik** [comment]
@bienell18,
There are movies working for me. Some not and linked to issue #34 .

**Comment by islandtj** [comment]
Aloha @cmik  and friends, tried to watch a couple of movies in the /Movie/Drama section (specifically, To Love Some Buddy) today and got the Kodi error, "This type of media is not supported" or something to that effect. I tried watching on my Roku TV on the Roku TFC.TV app and it played without issue. I have the Premium subscription and I am able to view on Roku. Would this be related to issue #34 ? Note, I have no issues watching any of the TV shows/dramas or news. Once again, mahalo for all your help @cmik !

**Comment by islandtj** [comment]
OK just viewed the Kodi online site and saw your reply:

> Sorry stylessos,
This feature is not implement yet.
I haven’t been able to implement inputstream adaptive. I’m missing something to be able to decrypt the video.

Hopefully a solution will arise, mahalo @cmik

**Comment by islandtj** [comment]
So for those who have a Fire stick/Firetv, a workaround is to log on and view TFC.TV on the Firestick's "Silk browser" until a viable media decryption process is identified.

**Comment by MALCHUSTVKODI** [comment]
HAS THIS ISSUE BEEN RESOLVE?.APPARENNTLY IS STILL ISSUE, i have a friend and me , with premium plus subs .playback not supported error coming when trying to watch a movie..will try to post log error..

**Comment by davidscherf** [comment]
Getting the same issue with movies, I have Premium Subscription but get the media not supported error
Not sure yet how to get the logs as I am new to Kodi

**Comment by cmik** [comment]
This issue will be fixed in version 1.4.0

**Comment by davidscherf** [comment]
Tested and Works, you are the best.

**Comment by Rokz021** [comment]
Cant play movies, input stream adaptive missing , please need help..

**Comment by cmik** [comment]
Hi @Rokz021 ,
Can you be more specific?
Which version of the add-on are you using? Do you have a free or premium plan?
What error message do you get when you try to play a movie?
Thanks in advance
