### ISSUE TITLE
Movies Missing

### ISSUE THREAD

**Issue by bolinao** [cmik/cmik.xbmc#3]
I found a problem on 0.58. when you go to movies more than half are not available to watch, the thumbnail for the movie is there, but when you open the folder it is empty, for example in the drama category "and I love you so" and most of the 'A" movies..

**Comment by codydude1** [comment]
Nuodtayo.tv has just released v1.7 that fixes the missing movies and has live tv. Its the most perfect version to date.

https://github.com/benaranguren/nuodtayo.tv/tree/master/plugin.video.tfctv

**Comment by cmik** [comment]
It seems that movies with empty folder are old movies which cannot be watched from website anymore.
I hope version 0.0.59 fixes this issue.
