### ISSUE TITLE
Tfc

### ISSUE THREAD

**Issue by craw2hell** [cmik/cmik.xbmc#31]
Hi cmik my tfc add on is not working . Getting TFc.tv error. error just came up today 9/4/18. Please help.

**Comment by arnel300** [comment]
I believe the problem is with the tfc.tv website...

Tfc.tv online is not working either.

Hopefully, they get their problem fixed.

**Comment by loceysgw** [comment]
I'm having an issue logging in also. it says I'm not logged in and then gives me a tfc.tv log in error message

**Comment by cmik** [comment]
@loceysgw ,
Please comment in issue #33 if you still have login issues
