### ISSUE TITLE
Any way to choose stream quality/resolution?

### ISSUE THREAD

**Issue by tagniam** [cmik/cmik.xbmc#32]
I saw that there used to be an option to choose the best stream quality [here](https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L301), but uncommenting that code block doesn't work.

**Comment by cmik** [comment]
@tagniam,
Yes that code is not finished. It was a test when we were having quality issues but I kept the code for later.

**Comment by cmik** [comment]
@tagniam 
ffmpeg automatically choose the best quality in the M3U8 file. But if you want to to limit the bitrate (then the quality) there is still a way :
https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L308
to 
https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L313
see https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-stream-packaging-rtmp-ingest-hds-and-hls-outputs-user-guide/GUID-58C3F955-1860-42C3-ACA9-985A84B88FE2.html

**Comment by cmik** [comment]
Option is available in 0.81 to choose the best stream.

**Comment by tagniam** [comment]
Thanks @cmik.
