### ISSUE TITLE
V .80 playback fail

### ISSUE THREAD

**Issue by Jranns** [cmik/cmik.xbmc#39]
Updated to .80 not working for me. Won't start videos.playback failed

**Comment by OCAMPOSP** [comment]
Same with me. Its was ok yesterday with the same version .80

**Comment by cmik** [comment]
Yes, I confirm. This issue started today : http error 403 from Akamai for m3u8 segment retrieval.
Proxy service and Apache proxy pass solutions don’t work.

**Comment by BigMiggen** [comment]
I appreciate all the work you guys have put into this over the last couple of years. With that said I have to say that I am now using a roku and will never look back. The tfc channel works great (and better quality streams it seems like). I would recommend everyone (including cmik) just to pick up a cheap roku stick this weekend, they're cheap for black friday/cyber monday. Let's let cmik and the others live their lives. Even if you just use it for tfc it's worth it. I still use my shields for everything else. On that note, peace out everyone and thank you for all the work fellas.

**Comment by MALCHUSTVKODI** [comment]
Roku is not the best device out there at the moment if its  just for tfc better option is still android devices, for me only,  so TFC addon for kodi is still better in my opinion only ...So far its working on my device..hopefully tfc addon will improve soon.Thanks cmik and the rest of the team for taking time to make tfc addon work as far as it can go..Salamat cmik at iba pa...Maligayang Pasko..

**Comment by benaranguren** [comment]
FYI @cmik, the version I have (v0.1.22) still streams fine using the proxy server.  However, it's not for anyone else to use because of how the authentication was implemented.  I'll see if I'll have time later to try v0.80.

**Comment by shakmaty** [comment]
@cmik @benaranguren
The "Range" http header seems to be the culprit.  My stream is working again after filtering it out.

**Comment by cmik** [comment]
Thank guys @shakmaty , @benaranguren .
I've removed all the headers except the user-agent as @benaranguren does in the v0.1.22.
I've also fixed the "force best stream" feature that was also not working.
version 0.0.81 : https://github.com/cmik/cmik.xbmc/commit/cd27fa90cf40a5510d49e80548de7b39a16149d1

**Comment by Kodigirl2274** [comment]
Please help can anyone tell me what to type in to get repo for tfc?

**Comment by Kodigirl2274** [comment]
I did try tinyurl.com/cmikRepo, but this doesn't work.

**Comment by Kodigirl2274** [comment]
I had to update my kodi to 17.6 with nolimits, now can't see anywhere in you tube how to install it in kodi.

**Comment by cmik** [comment]
@Kodigirl2274, you can download the zip with this link https://tinyurl.com/kodi-tfctvaddon-latest

**Comment by Kodigirl2274** [comment]
Hi @cmik, is this exactly I am going to type in the add source?

**Comment by Kodigirl2274** [comment]
Hi@cmik, I am afraid this doesn't work.

**Comment by Earl2000** [comment]
Thank you cmik it works again the 0.0.81 I just remove the Specific stream server and leave it blanc, it works both on windows and android.

**Comment by cmik** [comment]
@Kodigirl2274 ,
No, you have to download it, copy the zip on your device, then install from zip

**Comment by Kodigirl2274** [comment]
I am sorry to be a nuissance, but I am trying to do this in my smart tv, no idea how to download it through tv.

**Comment by Kodigirl2274** [comment]
Do I need to do it in downloader apps?

**Comment by MALCHUSTVKODI** [comment]
@kodigirl2274
Android smart tv?if you have kodi 17.6 installed on your android tv just use file manager!add source!

**Comment by Earl2000** [comment]
@Kodigirl2274 make nfs server or upnp from your PC then upload the Add-ons zip.file there.

**Comment by Kodigirl2274** [comment]
Hi @Malchustvkodi, that is what I needed, what should I type in to add source as I totally forgot what it was, I am ok to do this as long as I know the source to add, thank you😕

**Comment by MALCHUSTVKODI** [comment]
@Kodigirl2274
I have cmik repo hosted on my server but cannot post it here dm me on twitter @malchustv..

**Comment by Kodigirl2274** [comment]
I have amazon firetv box that is connected to my samsung smart tv and that is where I have my kodi.

**Comment by MALCHUSTVKODI** [comment]
So you are using amazon fire tv box i was under the impression it was an android tv.

**Comment by arnel300** [comment]
i have .81 butt still gives me error... http error 400 bad request...

failed tonplay

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cmik** [comment]
@Kodigirl2274 ,
For FireTv, you can use Downloader App to download the zip
or 
You can add this source : http://repo.cmik.me/

**Comment by ricardobothe** [comment]
> Thank you cmik it works again the 0.0.81 I just remove the Specific stream server and leave it blanc, it works both on windows and android.

Thank you all, thanks a lot CMIK.  0.81 now works.

@Kodigirl2274 ,  
I am using Raspbian (RPi3) and running OSMC.  First I tried to remove the Specific stream server and left the field (as what you have done) but it did not work.  Thus, I re-entered the https://o2-i and now it works  after re-starting the OSMC it works.

**Comment by cmik** [comment]
@ricardobothe ,
You can disable the option "Enable stream server modification". It will work the same.

**Comment by Kodigirl2274** [comment]
Hi @cmik thank you I was able to downloaded it but apparently now I am getting tfc.tv error unable to open it.

**Comment by cmik** [comment]
@Kodigirl2274 ,
Can you reboot your device or reboot Kodi (go out then go back)?

**Comment by Kodigirl2274** [comment]
Hi @cmik it does working now suddenly without  rebooting for some reason I don't know...many thanks for your patience, God bless😊

**Comment by makoychan** [comment]
Doesnt seem to auto update on mine, still .80 ver. Tried to manually update it butbbn its not seeing.81

**Comment by kulog99** [comment]
Added the new source and it updated to .81.  It's working again on our android TV. Thanks @cmik, @shakmaty , and @benaranguren.  You guys are the best.  Really appreciate your time and effort.   Happy wife again :)

**Comment by Jranns** [comment]
All good now great. Thx cmik. Works on shield and tcl roku tv .
