### ISSUE TITLE
Connection Timeout 

### ISSUE THREAD

**Issue by makoychan** [cmik/cmik.xbmc#4]
getting an error connection timeout after opening the addon..

**Comment by fonexpert8** [comment]
Hi CMIK,
Can you email me your contact info. I have a business proposal to you.

**Comment by rockers961** [comment]
Hi, I guess there is an issue now on viewing TFC on multiple devices at the same time?

**Comment by MALCHUSTVKODI** [comment]
yes same here sir ?a lot of people reporting connection timeout issues,,and time delay in loading the shows taking too long,,sometimes library of shows is empty,,thank you sir cmik,,when you have time kindly check it sir,,salamat ng marami,,we are waiting for your next release 0.0.59..hoep you find time to fix the issues and make improvements,,thanks again

**Comment by cmik** [comment]
I've released version 0.0.59. This one retrieve data from website and no more TFC API (timeouts).

**Comment by angel628** [comment]
@cmik How do I install version 0.0.59 with DOWNLOADER (just the shortened URL)?  Thanks

**Comment by makoychan** [comment]
Hi i just wanted to ask, how can i change the url that the tfc updates at, because now the original is coming from tv add ons but the one i have is .58 of cmik, i was able to change it by just installing it 1st on the pc then upload the my and download on my android box. But the url is still pointing to tv addons so now it doesnt auto update to .59 any ideas??

**Comment by cmik** [comment]
@makoychan,
I still have my own repo yet but working to add this addon to Kodi's official.
You have to install my repo so you can automatically have updates: https://github.com/cmik/cmik.xbmc/blob/master/downloads/repository.cmik.xbmc.addons/repository.cmik.xbmc.addons-0.0.1.zip?raw=true
Download and install it on your Kodi from Install from zip. Then select my repo, videos addons and install TFC.tv.
For this, you have to uninstall old TFC.tv addon before.

**Comment by angel628** [comment]
@cmik,
I was able to install version 0.0.59 but when I watch shows I'm getting notification "You are only allowed to watch a preview" which is 2mins long.  I have a TFC account configured in Settings.  How shud I fix this.  Thanks for your help.

**Comment by cmik** [comment]
@angel628 
It seems that you are not logged in.
I've released version 0.0.60 that checks if you are logged in. If not, it ask you and do it again.
Can you check?
Thanks in advance.

**Comment by angel628** [comment]
@cmik 
Once again I would like to thank you for all your efforts and hard work.  We certainly appreciate your work for the Filipino community in the US.  My entire family is very happy😊
