### ISSUE TITLE
CANT LOGIN TO SITE URL TIMEOUT ISSUE

### ISSUE THREAD

**Issue by MALCHUSTVKODI** [cmik/cmik.xbmc#41]
Hello .everyone am i the only one having url timeout issue error, cant log in to tfc site issue error..?thank you

**Comment by MALCHUSTVKODI** [comment]
log error sir cmik? salamat sa hardwork..paki check kung may time ka!thank you!using windows laptop kodi 17.6,same error on ftv pendant!!

**Comment by MALCHUSTVKODI** [comment]
https://www.dropbox.com/s/2xrik1wmbbteuox/tfclogerror.txt?dl=0

**Comment by MALCHUSTVKODI** [comment]
https://www.dropbox.com/s/2xrik1wmbbteuox/tfclogerror.txt?dl=0

**Comment by cmik** [comment]
Hi @MALCHUSTVKODI,
Can you try to delete the tfctv.cookie file in your addon user_data directory ?
Example : C:\Users\...\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.tfctv\tfctv.cookie

I've deleted your link post for security reason. Please change your TFC.tv credential password asap.
Thanks

**Comment by MALCHUSTVKODI** [comment]
> Hi @MALCHUSTVKODI,
> Can you try to delete the tfctv.cookie file in your addon user_data directory ?
> Example : C:\Users...\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.tfctv\tfctv.cookie
> 
> I've deleted your link post for security reason. Please change your TFC.tv credential password asap.
> Thanks

thanks for 
reply,wiil do asap!

**Comment by cmik** [comment]
@MALCHUSTVKODI ,
Do you still have issues?
If yes, can you try to install v1.0?
Thanks in advance.

**Comment by MALCHUSTVKODI** [comment]
@cmik i guess it solved the problem !but will report back in case i encounter an issue again!thanks a lot. What version 1.0 is that..??of the tfc addon?

**Comment by cmik** [comment]
Yes, TFC.tv addon is now at v1.0 and will soon be pushed in master branch.
More info : https://forum.kodi.tv/showthread.php?tid=317008&pid=2825462#pid2825462

**Comment by MALCHUSTVKODI** [comment]
@cmik salamat po, sa inyong patuloy na support sa addon,  where will you push updates ?still on github?or on your own server ,I can see that you now have your own server.Thanks for your hardwork,will test the pre release of the addon tfc v1.0.should we remove your repo ?

**Comment by cmik** [comment]
The repo will still be working on Github. My repo is use to simplify the download and installation.
Salamat sa tulong. 😉

**Comment by MALCHUSTVKODI** [comment]
@cmik on your github repo ,still showing 0.83 version..tried installing on top of it .but still works..do i need to go thru the set up process .as i skipped it?

**Comment by cmik** [comment]
It is recommended to optimize catalog cache (3rd option) (I think I will make it mandatory).
The catalog cache allow to load better fanarts and info, and optimize loading.
If you’ve skipped the setup, you’ll have to enable tools menu in the settings. And restart the quick setup.

**Comment by MALCHUSTVKODI** [comment]
@cmik , will do that then..salamat (merci beaucop)..
