### ISSUE TITLE
Subtitles? TFC.TV no longer hardcodes subtitles...

### ISSUE THREAD

**Issue by islandtj** [cmik/cmik.xbmc#46]
This might be a longshot request, but apparently, TFC has ceased hardcoding their English subtitles in their subtitled shows. Now you have to activate captions, to be able to view the subtitles when viewing in Roku, a PC, or a tablet.  I have subtitles enabled in Kodi but nothing shows up.  

Is this something that can be activated (i.e. captions) in your addon, CMIK?  Once again, mahalo for all your efforts!

**Comment by islandtj** [comment]
This is the reply I got from their online chat:

> We don't have an update if hardcoding or open subtitling will still be an option, but we still have programs under Subtitled Shows. As of now, closed subtitling will be present and allows you to turn on and off the videos subtitle. It is also not yet available on TFC Online app, but it is accessible through a phone or mobile browser. You may enable the subtitle option by clicking the "CC" logo at the lower corner of the video.

**Comment by cmik** [comment]
Hi @islandtj,
For your info, I've found a way to add the subtitles and I'm currently testing it.
I'll keep you posted in this thread.

**Comment by cmik** [comment]
@islandtj , @Jranns,
If you want to try: https://repo.cmik.me/tfc.tv/plugin.video.tfctv-1.3.0.zip
And give me a feedback.
Thanks in advance.

**Comment by islandtj** [comment]
Absolute wow, ©cmik!
You are indeed a champion! 1.3.0 worked like a charm. Big time mahalo to you cmik! I totally appreciate your efforts.  Again, MAHALO!!!

**Comment by Jranns** [comment]
Yes all working cmik. Your the man.thx heaps.cheers.

**Comment by Jranns** [comment]
Subtitles for  Shows dated today the 30th . Are no longer working .

**Comment by Jranns** [comment]
Will see if they work tomorrow.. maybe 1 day delayed  like old subtitles were.

**Comment by Jranns** [comment]
Yep just delayed a day. All good

**Comment by ronniew513** [comment]
How does this work please?

**Comment by Jranns** [comment]
You install it on a android tv or box. And then you subscribe  to tfc.tv.
its heaps cheaper than a tfc box.
