### ISSUE TITLE
i had some issues in version 0.0.59

### ISSUE THREAD

**Issue by Stevep27** [cmik/cmik.xbmc#5]
The message appears when i first opened it and the message says " connection time-out  https://tfc.tv"
i log-in on my tablet and it works.
any other thing i need to check?

i tried to update to version 0.0.59 unfortunately a message says "connection time-out" and i can only watch a preview version for all the shows. Kindly fixed the error. Thank you cmik...

**Comment by cmik** [comment]
What is the URL given for the timeout? And at what moment exactly?
It seems that you're not logged in that's why you can only watch previews.
Thanks in advance

**Comment by fonexpert8** [comment]
Hi Cmik,
Why the videos are not in HD quality anymore?

**Comment by Harrie1966** [comment]
This problem is from tfc.tv itself. They have changed a lot, and so unfortunately they are becoming more often. On my ipad too bad image. I hope they will solve this soon because this is not a question

**Comment by gwapoman** [comment]
Please see my comment on #8 for the fix and a temporary release from my fork. Enjoy!

**Comment by cmik** [comment]
@gwapoman
You're the man! Many thanks for the fix.
I'll merge and deploy as soon as I get to my computer ;)
