### ISSUE TITLE
Login error using latest version 1.3.3. . Cant login

### ISSUE THREAD

**Issue by Jranns** [cmik/cmik.xbmc#52]
Login error using latest version 1.3.3. . Cant login

**Comment by eric2three** [comment]
Same here. Also having the same problem.

**Comment by cmik** [comment]
Hi @Jranns, @eric2three,
Do you have logs?
Login process is working on mine at this time.
Maybe TFC was doing some change because show page on website has sightly changed so it produces an error for the addon on shows content display.
Thanks in advance.

**Comment by seana213** [comment]
Same here..can't play..

**Comment by m1k31804** [comment]
You can login, open all categories just not play the links. 
Thanks.

**Comment by Jranns** [comment]
Still v same.

**Comment by glonsdale2018** [comment]
Also having the same problem. Can login and see all categories. But gives error if trying to start a show.

Thank you.

**Comment by cmik** [comment]
Hi,
I’m working on a fix. Hope to deploy it soon.

**Comment by sdstreams** [comment]
thanks @cmik for keep this addon alive my family really appreciates it

**Comment by seana213** [comment]
Thanks @cmik

**Comment by TFC1970** [comment]
Hello All,
can anyone help with step by step instructions on how to reload TFC to kodi on my firestick,, as i  
uninstalled  it,  now i cant figure out how to re install again, i guess thats what happens when you are a Caveman like me, slow at tech stuff, thanks

**Comment by cmik** [comment]
New version 1.3.4 is out and fixes this issue
https://github.com/cmik/cmik.xbmc/commit/b53aaeeead3c67d3f05e4e5660f1f77a66e1a042

**Comment by Jranns** [comment]
All good now cmik. Thx heaps. Salamat.

**Comment by johnfred1972** [comment]
Thanks.

 Going on configure addon i can only see update 1.3.3 ? How to upgrade to
1.3.4? Would be helpful so my wife is happy again and can watch her
shows... :) (life safer)

**Comment by Jranns** [comment]
Its there in downloads.
