### ISSUE TITLE
Error 403 forbidden 

### ISSUE THREAD

**Issue by Jranns** [cmik/cmik.xbmc#54]
Error when selecting shows  Forbidden error  403

**Comment by bidi1268** [comment]
Same here😔error 403.
playback failed. Check log for more

**Comment by BigMiggen** [comment]
I think it's a server side problem. My legit roku tfc channel is having playback issues too. Give it a day, they are aware. I just got off chat with them

**Comment by Jranns** [comment]
But the tfc.tv website is working fine. Im using it at the moment.

**Comment by sdstreams** [comment]
same here first I was getting login issues it was saying invalid when it was not no getting error 403. nothing is showing in By Category.

**Comment by arnel300** [comment]
I just noticed the problem today...
it allows access to all the menu item but it will not play the
episodes/videos... error 403 forbidden... can't play the selected item...

thanks cmik.

**Comment by cmik** [comment]
Hi all,
I've released the hotfix version https://github.com/cmik/cmik.xbmc/releases/tag/1.4.1 that normally fixed the playback issue with the 403 error. It seems it requires some headers to be allowed to retrieve stream files. You also need to restart your Kodi.
If you already installed the 1.4.1 previously, you'll have to reinstall it.
Thanks for your feedback.

**Comment by sdstreams** [comment]
update working! thanks for the fix

**Comment by Jranns** [comment]
Thx cmik all good now.

**Comment by lazean214** [comment]
Kodi leia still playing preview

**Comment by jamesrad4732** [comment]
sir how about inputstream.adaptive some videos need it. any idea where we can get it? TIA!

**Comment by cmik** [comment]
@lazean214,
Preview means that you are not logged in. Please check your credentials.

**Comment by cmik** [comment]
@jamesrad4732,
Latest version of the addon already implements inputstream.adaptive.
Playback issue on some videos is because of a 403 error when retrieving the manifest. I reproduce it on a Postman but can’t get rid of it. I don’t have a fix for the moment.

**Comment by jamesrad4732** [comment]
@cmik thank you for everything you do!

**Comment by m1k31804** [comment]
Error 40, after I login why?

**Comment by yoseminao** [comment]
> 
> 
> @jamesrad4732,
> Latest version of the addon already implements inputstream.adaptive.
> Playback issue on some videos is because of a 403 error when retrieving the manifest. I reproduce it on a Postman but can’t get rid of it. I don’t have a fix for the moment.

@cmik add header authorization.

**Comment by cmik** [comment]
thanks @yoseminao.
The manifest doesn't use authorization header.
It seems it was Kodi user agent that raised the 403 error from Akamai. They have blocked it very quickly (just after the 1.4.0 version).
Now I've tried to use the proxy service to change the user agent, but I now have this error :

> 21:03:57.965 T:20128   DEBUG: AddOnLog: InputStream Adaptive: Download http://127.0.0.1:6531/?url=https%3A//amssabscbn.akamaized.net/... finished
> 21:03:57.965 T:20128    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Type: VOD, Download speed: 0.0000 Bytes/s
> 21:03:57.966 T:20128   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
> 21:03:57.969 T:20128   DEBUG: Previous line repeats 1 times.
> 21:03:57.970 T:20128   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
> 21:03:57.977 T:20128   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\cmik\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
> 21:03:57.977 T:20128   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed

**Comment by yoseminao** [comment]
> 
> 
> thanks @yoseminao.
> The manifest doesn't use authorization header.
> It seems it was Kodi user agent that raised the 403 error from Akamai. They have blocked it very quickly (just after the 1.4.0 version).
> Now I've tried to use the proxy service to change the user agent, but I now have this error :
> 
> > 21:03:57.965 T:20128   DEBUG: AddOnLog: InputStream Adaptive: Download http://127.0.0.1:6531/?url=https%3A//amssabscbn.akamaized.net/... finished
> > 21:03:57.965 T:20128    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Type: VOD, Download speed: 0.0000 Bytes/s
> > 21:03:57.966 T:20128   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
> > 21:03:57.969 T:20128   DEBUG: Previous line repeats 1 times.
> > 21:03:57.970 T:20128   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
> > 21:03:57.977 T:20128   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\cmik\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
> > 21:03:57.977 T:20128   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed

but it works. I tried using the authorization header from license url and it works.

**Comment by cmik** [comment]
Hi all,
Just released hotfix version 1.4.3 (https://github.com/cmik/cmik.xbmc/releases/tag/1.4.3) that fixes playback issues on encrypted streams.

Thanks in advance for your feedbacks.

@yoseminao, to fix the issue I had to set the header's user-agent to not use Kodi's and the content-type. I was already using Authorization header for the license server URL (since version 1.4.0).

**Comment by cmik** [comment]
New version 1.4.6 that fixes the playback issue on encrypted streams (again): some headers became mandatory.
