### ISSUE TITLE
can only watch preview 

### ISSUE THREAD

**Issue by hyperjm29** [cmik/cmik.xbmc#56]
wanted to watch a teleserye but a notification would pop up and say i can only watch a preview of the episode which is only 2 minutes long. much appreciated for your help.

Thank you :)

**Comment by cmik** [comment]
Hi,
Have you a free or a premium plan?
Lots are previews in free plan (see TFC.tv website for more details).
If you are a premium, check if the add-in welcomes you when you start it. If not, please double check your credentials (check for space or else).
Check that you can access « My account » in the main menu and you can view your subscriptions.
Hope this can help.
And thanks for using this add-on.

**Comment by hyperjm29** [comment]
I have a free account.
So you can only watch the free shows of tfc.tv in the kodi addon?

**Comment by cmik** [comment]
Yes, that’s right. It allows to access to the exact content as TFC.tv website according to your account plan.

**Comment by hyperjm29** [comment]
ok thanks for info
