### ISSUE TITLE
TFC.TV v1.4.10 / Login Issue

### ISSUE THREAD

**Issue by C-Flick** [cmik/cmik.xbmc#59]
Since this upgrade was automatically installed in my RVeal Tv box with Kodi 18.7 Leia I'm getting TFC.TV Error  Check log for more information. Pls. Help.

**Comment by johnfred1972** [comment]
Indeed, same here. Uninstall it and install the 1.3.7 version.

 Works.

**Comment by C-Flick** [comment]
uninstall v1.4.10 and install 1.3.7 version, Http error 403

**Comment by cmik** [comment]
Hi @C-Flick ,
Can you try to install 1.4.10 again and check "Login with SSO" is disabled?
If you still have the error, try to enable it, validate settings, then go back and disable it again.
Thanks in advance for your feedbacks.

**Comment by C-Flick** [comment]
Hello there, I've tried to Login with SSO enable, I got "Http error 403" when I disable the SSO back to "TFC Error check the log for more information". I've done a lot of trouble shooting uninstall and re install the Kodi, enable and disable some features in TFC advance settings and  got the same result. All my Rveal adds on are working except this new TFC v1.4.10 update, and i have no clue,  Thanks for your quick respond.

**Comment by eric2three** [comment]
Any update on our tfc add on? Still getting error

**Comment by C-Flick** [comment]
Still no luck Eric.

**Comment by cmik** [comment]
Hi @eric2three and @C-Flick,

It's working fine on my side.
Can you share some logs? Beforehand, enable debug mode on the TFC.tv add-on advanced settings and set level to INFO, then retry to launch the add-on.

Do you have a TFC.tv or a Kapamilya account? What do you get when you login directly to https://tfc.tv/user/login on a browser?

Thanks in advance.

**Comment by C-Flick** [comment]
Hello there,

 

   My TFC.tv Kapamilya  account work in my desktop PC and also in my Roku , I've also attached a portion of the Log file with TFC.tv error hope this help. Yeah.. I don't understand this update my two brother in laws from Vienna Austria are running the same version with no problem. I'm in USA so I don't know if this something to do with the region.

 

Thanks a lot for helping me to resolve this issue.

**Comment by eric2three** [comment]
I am using my kapamilya usernamr and pw.. not my email address

**Comment by cmik** [comment]
I've tested :

- with a TFC.tv account (FREE / PREMIUM) and a Kapamilya account => all good.

- Tested with VPN in U.S => no problem

@C-Flick , I don't see your logfile.

**Comment by thebrumby** [comment]
Hi Cmik,

I have the same issue and can not sign in with my Kapamilia account details.

Can anyone tell me where to find the log file for Fire TV / Kodi?

Thanks

**Comment by C-Flick** [comment]
> I've tested :
> 
> * with a TFC.tv account (FREE / PREMIUM) and a Kapamilya account => all good.
> * Tested with VPN in U.S => no problem
> 
> @C-Flick , I don't see your logfile.

Sorry I've attached it into my reply e-mail to you. I will attached it here in PDF
THanks.
[TFC error log.pdf](https://github.com/cmik/cmik.xbmc/files/4760872/TFC.error.log.pdf)

**Comment by C-Flick** [comment]
Hi Thebrumby,

 

I'm not familiar on Fire TV, but here is the way to view log file" ADD-Ons/ Install from Repository/Kodi Add-On Repository/Program Add-On, select Log Viewer for Kodi to view Log, Kodi Logfile Uploader  to upload the Log file".

 

Thanks

**Comment by thebrumby** [comment]
Perfect thanks. I’m seeing this error in the log. 



Get directory error and global name ”lang” is not defined.

**Comment by cmik** [comment]
@thebrumby, @C-Flick, @eric2three 
Can you test this version  https://repo.cmik.me/tfc.tv/plugin.video.tfctv-pre1.4.11.zip ?
It has the fix for the lang error.
But I don't think this will fix your issue because the error happens when login has failed.

**Comment by thebrumby** [comment]
Hi Cmik,

Just to let you know that in an attempt to install 1.4.11 I removed my old install and chose to delete all the app data. 

When I reinstalled it still looks like 1.4.10 according to the version number. But I reentered my Kampamilia account details and it’s working fine. 

Thank you.

**Comment by cmik** [comment]
@thebrumby ,
Thanks for the feedback.
I'll wait for @C-Flick / @eric2three feedbacks before I make a new release.

**Comment by C-Flick** [comment]
Hi cmik,
I did  @thebrumby comments and it's working fine.

Thank you very much

**Comment by cmik** [comment]
v1.4.11 has been released

**Comment by thebrumby** [comment]
Updated and working fine thank you :)

**Comment by C-Flick** [comment]
Also updated and working fine, except the Live News ANC Live streaming & Teleradyo
 Thank you.

**Comment by cmik** [comment]
Thanks for the feedbacks.
I'm closing this issue and I've created a new one for live streams issue [here](https://github.com/cmik/plugin.video.tfctv/issues/2)

**Comment by eric2three** [comment]
Many thanks

**Comment by C-Flick** [comment]
Thanks a lot..

Sent from my iPhone

On Jun 12, 2020, at 12:08 AM, cmik <notifications@github.com> wrote:

﻿
Thanks for the feedbacks.
I'm closing this issue and I've created a new one for live streams issue here
