### ISSUE TITLE
New addon 0.59  Resolution

### ISSUE THREAD

**Issue by Harrie1966** [cmik/cmik.xbmc#6]
The addon works fine. Only the resolution has gone back from 720 to 480. Can not wait to look at an HD TV

**Comment by Harrie1966** [comment]
![img_0530](https://user-images.githubusercontent.com/18618129/27763895-d259e13c-5e8c-11e7-87c6-389e1db97115.PNG)

**Comment by Harrie1966** [comment]
This problem is from tfc.tv itself. They have changed a lot, and so unfortunately they are becoming more often. On my ipad too bad image. I hope they will solve this soon because this is not a question

**Comment by cmik** [comment]
@Harrie1966 
I'm testing a lot to identify what has changed. It is a little difficult as expected and I've not found yet.
I'm still investigating.

**Comment by nuttyclub** [comment]
Hi @cmik Just wanna say thanks for all the help. Most of us really appreciate what you're doing. :)

**Comment by Harrie1966** [comment]
Hi @cmik 

Thank you in advance for your effort. I think it's with TFC itself. I have tried the app and there is a sharp picture. So i had unpacked the monkey in andriod studio. And watched the video settings. There are many settings. Unfortunately I do not understand much about it. I hope you can find it. But think there's something wrong with TFC.

<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen
   xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:attr="http://schemas.android.com/apk/res/com.absi.tfctv">

   <PreferenceScreen
       android:title="Basic">

       <CheckBoxPreference
           android:title="@ref/0x7f0b01ed"
           android:key="useUDP"
           android:summary="@ref/0x7f0b01ee"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b01f0"
           android:summaryOff="@ref/0x7f0b01ef" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01e9"
           android:key="useExternalPD"
           android:summary="@ref/0x7f0b01ea"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b01ec"
           android:summaryOff="@ref/0x7f0b01eb" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01c0"
           android:key="enabledtWebvtt"
           android:defaultValue="true"
           android:summaryOn="@ref/0x7f0b01c2"
           android:summaryOff="@ref/0x7f0b01c1" />

       <com.nexstreaming.app.apis.PreferenceEditTextFormatted
           android:title="@ref/0x7f0b01d2"
           android:key="@ref/0x7f0b01d4"
           android:defaultValue="@ref/0x7f0b01d3"
           attr:inputformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$"
           attr:completeformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b017b"
           android:key="ignoreTextmode"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b017c"
           android:summaryOff="@ref/0x7f0b017d" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110019"
           android:title="@ref/0x7f0b01c5"
           android:key="replayMode"
           android:summary="summary"
           android:defaultValue="2"
           android:entryValues="@ref/0x7f11001a" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01f3"
           android:key="WebvttWaitOpen"
           android:defaultValue="true"
           android:summaryOn="@ref/0x7f0b01f5"
           android:summaryOff="@ref/0x7f0b01f4" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01a6"
           android:key="HLSRunModeStable"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b01a8"
           android:summaryOff="@ref/0x7f0b01a7" />

       <com.nexstreaming.app.apis.PreferenceEditTextFormatted
           android:title="@ref/0x7f0b01bd"
           android:key="@ref/0x7f0b01bc"
           android:summary="summary"
           android:defaultValue="@string/0xf"
           attr:inputformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$"
           attr:completeformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$" />

       <com.nexstreaming.app.apis.PreferenceEditTextFormatted
           android:title="@ref/0x7f0b01bf"
           android:key="@ref/0x7f0b01be"
           android:summary="summary"
           android:defaultValue="@string/0xf"
           attr:inputformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$"
           attr:completeformat="^[[a-z][A-Z][0-9][\-\_\:\/\.\s]]{1,}?$" />

       <com.nexstreaming.app.apis.PreferenceEditTextFormatted
           android:title="@ref/0x7f0b01ca"
           android:key="@ref/0x7f0b01c9"
           android:summary="summary"
           android:defaultValue="0"
           attr:inputformat="^[[0-9]]{1,}?$"
           attr:completeformat="^[[0-9]]{1,}?$" />

       <com.nexstreaming.app.apis.PreferenceEditTextFormatted
           android:title="@ref/0x7f0b01cc"
           android:key="@ref/0x7f0b01cb"
           android:summary="summary"
           android:defaultValue="0"
           attr:inputformat="^[[0-9]]{1,}?$"
           attr:completeformat="^[[0-9]]{1,}?$" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b019c"
           android:key="@ref/0x7f0b0199"
           android:defaultValue="true"
           android:summaryOn="@ref/0x7f0b019b"
           android:summaryOff="@ref/0x7f0b019a" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="@ref/0x7f0b01ad"
           android:key="@ref/0x7f0b01ac"
           android:defaultValue="0"
           interval="1"
           max="2048"
           min="0"
           unitLabel="kbps" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="@ref/0x7f0b01b1"
           android:key="@ref/0x7f0b01b0"
           android:defaultValue="0"
           interval="1"
           max="2048"
           min="0"
           unitLabel="kbps" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110008"
           android:title="@ref/0x7f0b0179"
           android:key="captionMode"
           android:summary="summary"
           android:defaultValue="0"
           android:entryValues="@ref/0x7f110009" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110016"
           android:title="@ref/0x7f0b01ab"
           android:key="logLevel"
           android:summary="summary"
           android:defaultValue="0"
           android:entryValues="@ref/0x7f110016" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110017"
           android:title="@ref/0x7f0b01c3"
           android:key="renderMode"
           android:summary="summary"
           android:defaultValue="Auto"
           android:entryValues="@ref/0x7f110018" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f11000e"
           android:title="@ref/0x7f0b0183"
           android:key="colorSpace"
           android:summary="summary"
           android:defaultValue="1"
           android:entryValues="@ref/0x7f11000f" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01a2"
           android:key="eyePleaser"
           android:summary="@ref/0x7f0b01a3"
           android:defaultValue="true"
           android:summaryOn="@ref/0x7f0b01a5"
           android:summaryOff="@ref/0x7f0b01a4" />

       <CheckBoxPreference
           android:title="@ref/0x7f0b01cd"
           android:key="StatisticsMonitor"
           android:summary="@ref/0x7f0b01ce"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b01d0"
           android:summaryOff="@ref/0x7f0b01cf" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="Buffering Time"
           android:key="bufferTime"
           android:defaultValue="0"
           interval="0.25"
           max="10"
           min="0"
           unitLabel="seconds" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="AV Sync Offset"
           android:key="AVSyncOffset"
           android:defaultValue="0"
           interval="0.05"
           max="1"
           min="-1"
           unitLabel="seconds" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="Video Display Wait Offset"
           android:key="VideoDisplayWait"
           android:defaultValue="-50"
           interval="10"
           max="0"
           min="-100"
           unitLabel="msec" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="Video Display Skip Offset"
           android:key="VideoDisplaySkip"
           android:defaultValue="70"
           interval="10"
           max="500"
           min="0"
           unitLabel="msec" />
   </PreferenceScreen>

   <PreferenceScreen
       android:title="@ref/0x7f0b0101">

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110013"
           android:title="@ref/0x7f0b00ff"
           android:key="@ref/0x7f0b00ff"
           android:summary="summary"
           android:defaultValue="0"
           android:entryValues="@ref/0x7f110012" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110011"
           android:title="@ref/0x7f0b00fd"
           android:key="@ref/0x7f0b00fd"
           android:summary="summary"
           android:defaultValue="0"
           android:entryValues="@ref/0x7f110012" />
   </PreferenceScreen>

   <PreferenceScreen
       android:title="Debug Log">

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110010"
           android:title="@ref/0x7f0b0185"
           android:key="@ref/0x7f0b0184"
           android:summary="summary"
           android:defaultValue="-1"
           android:entryValues="@ref/0x7f110010" />

       <com.nexstreaming.app.apis.ListPrefWithSummary
           android:entries="@ref/0x7f110010"
           android:title="@ref/0x7f0b0190"
           android:key="@ref/0x7f0b018f"
           android:summary="summary"
           android:defaultValue="-1"
           android:entryValues="@ref/0x7f110010" />

       <com.nexstreaming.app.apis.CheckBoxDialogPreference
           android:title="@ref/0x7f0b018e"
           android:positiveButtonText="@ref/0x7f0b0142"
           android:negativeButtonText="@ref/0x7f0b00da" />
   </PreferenceScreen>

   <PreferenceScreen
       android:title="Trackdown">

       <CheckBoxPreference
           android:title="@ref/0x7f0b01dc"
           android:key="@ref/0x7f0b01de"
           android:summary="@ref/0x7f0b01dd"
           android:defaultValue="false"
           android:summaryOn="@ref/0x7f0b01e0"
           android:summaryOff="@ref/0x7f0b01df" />

       <com.nexstreaming.app.apis.SliderPreference
           android:title="Trackdown Threshold"
           android:key="@ref/0x7f0b01e1"
           android:dependency="@ref/0x7f0b01de"
           android:defaultValue="20"
           interval="1"
           max="100"
           min="0"
           unitLabel="percents" />
   </PreferenceScreen>
</PreferenceScreen>

**Comment by MALCHUSTVKODI** [comment]
Just want to say thank u to cmik and gwapoman...salamat ng marami mga kababayans...keep it up....thanks for the fix...Mabuhay!!

**Comment by cmik** [comment]
Many thanks!
