### ISSUE TITLE
TFC ver. 1.5.0

### ISSUE THREAD

**Issue by CFlick72** [cmik/cmik.xbmc#63]
[Log File.pdf](https://github.com/cmik/cmik.xbmc/files/6066938/Log.File.pdf)
Hi Cmik,

My Kodi 18.9 was auto updated to new Ver.19.0 and wiped out all my adds on, and it shows all the incompatible adds on and TFC is one of them. I've deleted the new Kodi version and reinstalled  the Kodi 18.9 but somehow the TFC is not working. I cannot log in to my account. I'm getting "YOUR NOT LOGGED INTO TFC" message, and when I click on YES to Log into my account I got "YOUR ACTUALLY NOT CONNECTED" information. I've attached the log file with Debug Info on in pdf file. Your quick respond will be much appreciated.

Thanks in advance

**Comment by jheff2311** [comment]
Hello, just wanted to ask have you solved the issue already?i have the same error and I don’t know what to do.
