### ISSUE TITLE
v1.5.0 Live Channels

### ISSUE THREAD

**Issue by sdstreams** [cmik/cmik.xbmc#64]
have newest version installed and all shows and movies play fine but the live channels are no longer working for me. Running Kodi 18 and account is current.

**Comment by cmik** [comment]
Hi @HenioH,
Do you still have the same problems with last version 1.6.1?
On my side, live channels works perfectly even in 1.5.0

**Comment by sdstreams** [comment]
Live channels are working again on version 1.6.1. Thank you for your time and great work.

**Comment by cmik** [comment]
Thanks for your feedback
