### ISSUE TITLE
TFC.Tv error Check log for more

### ISSUE THREAD

**Issue by loceysgw** [cmik/cmik.xbmc#66]
Can't log in the my account on 1.6.1

**Comment by cmik** [comment]
Hi @loceysgw ,
can you test 1.6.2 version? See here https://github.com/cmik/plugin.video.tfctv/issues/8
Thanks for your feedback.

**Comment by Ilovetfc** [comment]
Do you have idea why my Firestick would have TFC error when I entered my
account with TFC subscription?

I am using Kodi 18.6.

Thanks,

Irving

**Comment by loceysgw** [comment]
All working now.Thank you 😊 


Sent from Yahoo Mail for iPhone


On Sunday, July 18, 2021, 1:41 AM, cmik ***@***.***> wrote:




Hi @loceysgw ,
can you test 1.6.2 version? See here cmik/plugin.video.tfctv#8
Thanks for your feedback.
