### ISSUE TITLE
Assistance Concurrent Devices

### ISSUE THREAD

**Issue by sdstreams** [cmik/cmik.xbmc#67]
Idea: Getting maximum concurrent devices error now.

Hello, once it switched over from Kapamilya website to iWant TFC site I no longer am able to use it in multiple rooms at the same time. On iWantTFC website it only allows 2 devices now. Is there a way to bypass this device count with a proxy in the addon? I see there's already one but would happen if I add my own so it reads always as one IP accessing the account?

**Comment by cmik** [comment]
Hi @sdstreams ,
Sorry for the response delay.
Maximum concurrent devices is now more strict with the latest iWantTFC. I don't think there is a work around with IP address or with the user agent.
