### ISSUE TITLE
Can only watch preview of shows

### ISSUE THREAD

**Issue by angel628** [cmik/cmik.xbmc#7]
@cmik,
Hi,
I was able to install version 0.0.59 but when I watch shows I'm getting notification "You are only allowed to watch a preview" which is 2mins long. I have a TFC account configured in Settings. How shud I fix this. Thanks for your help.

**Comment by Harrie1966** [comment]
Remove your email and password. En restart setting and put your email and pasword again en now its working.

**Comment by cmik** [comment]
@angel628
It seems that you are not logged in.
I've released version 0.0.60 that checks if you are logged in. If not, it ask you and do it again.
Can you check?
Thanks in advance.

**Comment by angel628** [comment]
@cmik 
I'm using downloader to install, can you pls give me shortened URL to update to .60.  I've installed your repo: https://github.com/cmik/cmik.xbmc/blob/master/downloads/repository.cmik.xbmc.addons/repository.cmik.xbmc.addons-0.0.1.zip?raw=true, but it doesn't show option to update from .59 to .60.

Thanks in advance really appreciate all your efforts and help with TFC.

**Comment by angel628** [comment]
@cmik 
I was able to install version .60 thru your repo.  I deleted file then re download repo and was able to install version .60. 

However, when I open TFC I get a message that I'm not log in, and Do i want to log in as (my email acct) and if I click yes I'm getting TFC error message (Check log info).

**Comment by angel628** [comment]
@cmik 
It's ok now with .60.  I deleted email and password, restart Kodi, then reconfigure my email/password in settings.

Thanks for all your help!
