### ISSUE TITLE
Unable to download latest GMA Addon 

### ISSUE THREAD

**Issue by jrm25** [cmik/cmik.xbmc#70]
Hi, Just want to say Im a fan of your work, Im unable to download the latest version of GMA on Kodi 19.3 its unable to load because of a dependency for script.module.parsedom for xbmc plugins. I've tried to tweak it with no luck. has anyone had problems with the addon after migration. Right now I have a box that still utilizes 18.9 so Im still able to watch the addon its only when I go to 19.3. Let me know there's something Im missing. 

JRM

**Comment by cmik** [comment]
Hi @jrm25,
Thanks. 
GMA.tv add-on version for kodi 19 is not available yet. I'll try to take some time to finish the work. I'll keep you posted through this thread.
Regards

**Comment by jrm25** [comment]
Thanks cmik yah I was trying to see if I can tweak it a bit, but I’m still learning python as I go, I tried comparing the source files on what changed between the old tfc addon and some similaries between the addon.xml and the default.py file. For now I just copied the original source file and I put it on my bucket just for me to go with :-)

**Comment by cmik** [comment]
@jrm25,
GMA.tv version 1.0.0 is released : https://github.com/cmik/plugin.video.gmatv/releases/tag/v1.0.0
Your feedbacks are welcomed.
Thanks.

**Comment by cmik** [comment]
I'm closing this issue here and follow it in the GMA.tv project : https://github.com/cmik/plugin.video.gmatv/issues/1
