### ISSUE TITLE
Pixelation issue or resolution issue on android box only !

### ISSUE THREAD

**Issue by MALCHUSTVKODI** [cmik/cmik.xbmc#8]
Hello cmik ,just to report this is what i have noticed i tested your latest release 0.0.60 on a laptop win10 kodi 17.3 no issues on video quality..while on android box all videos 480p and blurry...iam a premium subscriber ..thanks for your time and effort..

**Comment by MALCHUSTVKODI** [comment]
All is working fine now no timeouts ..shows loads quicker now..only the resolution issue on android boxes which i don't understand ?..whereas your previous versions was ok on both platforms...win10 or android boxes...thanks

**Comment by gwapoman** [comment]
@cmik may fix ako dito. if you still need it i'll open a pull request later

**Comment by kulog99** [comment]
Also experiencing poor video quality  on 0.0.60 on Android TV.  Thanks in advance if you have a fix.

**Comment by angel628** [comment]
Same here, poor video quality with Amazon Fire TV on 0.0.60. Thanks.

**Comment by seana213** [comment]
Poor video quality din sa android tv box ko..

**Comment by arcangel919** [comment]
I think all Android platform have pixelation or video quality issues.  Hoping there would be a fix soon.  Thanks guys.

**Comment by eric2three** [comment]
Patiently waiting for an update from cmik. I hope he can fix this issue asap. Maraming salamat in advance, i sure you can fix this problem and make all of us happy.

**Comment by gwapoman** [comment]
Sorry I've been a bit busy. I've submitted the pull request.

Guys if you want the fix now you can get the installer (a temp release) from my fork: ~~https://github.com/gwapoman/cmik.xbmc/raw/dev/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.60.zip~~

[Edit- use this instead:]
https://github.com/gwapoman/cmik.xbmc/raw/dev/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.60-hd.zip

Otherwise just wait for @cmik to merge the fix here and release a new version

**Comment by rockers961** [comment]
Hi @gwapoman I still have pixelation issue from your fork. I did a clean install and cleared cache and cookies as well. am I missing something? Thanks a lot.

**Comment by jcollinsjr** [comment]
Just to report I'm also still seeing pixelization with the latest fork. I
did a clean install, but still having issues. Thank you for all support in
trying to get this to work.

**Comment by eric2three** [comment]
@gwapoman, I tried using your temp release but its still blurry..

**Comment by gwapoman** [comment]
Sorry I posted the wrong link. Please use this https://github.com/gwapoman/cmik.xbmc/raw/dev/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.60-hd.zip

**Comment by jcollinsjr** [comment]
I'm happy to report the HD stream works. Thank you so much! Have a happy 4th of July!

On Jul 4, 2017 11:48 AM, "gwapoman" <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry I posted the wrong link. Please use this https://github.com/gwapoman/cmik.xbmc/raw/dev/downloads/plugin.video.tfctv/plugin.video.tfctv-0.0.60-hd.zip

**Comment by eric2three** [comment]
Maraming salamat. Working great now.

**Comment by rockers961** [comment]
Working Great. Thanks Man.!!!

**Comment by apps2011** [comment]
working great here as well. Thnaks

**Comment by Dave4jc** [comment]
Tv patrol and regional news does not work in my Sony android tv. Could you please check yours if you have the same problem on different devices.

**Comment by MALCHUSTVKODI** [comment]
Yes some have reported not all sections work..live channels does not...so will have to wait now..but still thanks for the effort gwapoman...salamat...may kasama na si cmik in fixing all the issues...2 is better than one...thanks..

**Comment by Dave4jc** [comment]
I guess we have to wait now but great job CMIK. God bless you. Mabuhay ka!

**Comment by Harrie1966** [comment]
Yes working good now thank you.

**Comment by cmik** [comment]
Thanks to @gwapoman ! He's the one !

**Comment by cmik** [comment]
@gwapoman 
I've merge your fix. Many thanks again.
But I kept all the resolution in the m3u8 file (https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L285) for users with low bandwidth.

**Comment by arcangel919** [comment]
All is working except news on my amazon fire tv.  Will there be a fix for this too? Thanks cmik amd gwapoman for the efforts.  

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 4, 2017 at 12:41 PM, cmik<notifications@github.com> wrote:   
@gwapoman
I've merge your fix. Many thanks again.
But I kept all the resolution in the m3u8 file (https://github.com/cmik/cmik.xbmc/blob/master/plugin.video.tfctv/default.py#L285) for users with low bandwidth.

**Comment by arcangel919** [comment]
Pixelization has been reaolved but the news section particularly tv patrol does not open up.  Any fix on this cmik and gwapoman? Thanks for all your efforts.

**Comment by cmik** [comment]
@arcangel919 
News section is working on my side (Global news / Regional news / Current affairs). A very few times I had a playback error (ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer) but when I try again, it works.

**Comment by arcangel919** [comment]
Thanks cmik.  Probably need to clear cache.  I will try it again later.  A million thanks to you. 

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 4, 2017 at 2:59 PM, cmik<notifications@github.com> wrote:   
@arcangel919
News section is working on my side (Global news / Regional news / Current affairs). A very few times I had a playback error (ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer) but when I try again, it works.

**Comment by Dave4jc** [comment]
I tried every possible way. Tfc is installed on mutiple devices.firestick, sony tv, android box but all shows are all 2minute preview please hlep

**Comment by cmik** [comment]
@Dave4jc,
1. Can you try to modify your password on TFC.tv website then on your addon? Some says that it could be the password that is too short.
2. If not, try to remove your credentials from addon then restart addon. Put again your credentials then restart addon.
Hope this can help.

**Comment by Dave4jc** [comment]
done this as well but no luck

**Comment by kulog99** [comment]
@Dave4jc - the last time I had this 2 min preview issue is it got fixed after I cleared the cache in kodi via the Indigo utility.  Hope this helps.

**Comment by angel628** [comment]
@Dave4jc 
This happened to me, when you delete credentials in settings, first remove password before email bcuz when you delete email first then you don't have the option to delete password.  Restart Kodi then reconfigure email/password.

Or another thing, make sure you have the right password, like me my sister changed the password, (just omitting the last character) but didn't tell me so I was knocking my brains trying to fix it and couldn't.  So to simplify, just change password online, then reconfigure your email/password in TFC/Kodi.

I hope this will help.
